### PR TITLE
test no mypyc

### LINKED ISSUE #11: `mypy` is just plain Mypy
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

MWE:

```
pixi init
pixi add basedmypy
pixi shell
mypy --version
```

Expected behaviour:

```
basedmypy 2.7.0 (compiled: yes)
Based on mypy 1.13.0
```

Actual behaviour:

```
mypy 1.13.0 (compiled: yes)
```

Running `mypy` appears to just be (non-based) Mypy.

### Installed packages

```shell
Package                Version    Build               Size       Kind   Source
basedmypy              2.7.0      pyhd8ed1ab_0        66.3 KiB   conda  basedmypy-2.7.0-pyhd8ed1ab_0.conda
basedtyping            0.1.10     pyhd8ed1ab_0        22 KiB     conda  basedtyping-0.1.10-pyhd8ed1ab_0.conda
bzip2                  1.0.8      h99b78c6_7          120 KiB    conda  bzip2-1.0.8-h99b78c6_7.conda
ca-certificates        2024.8.30  hf0a4a13_0          154.8 KiB  conda  ca-certificates-2024.8.30-hf0a4a13_0.conda
cctools_osx-arm64      1010.6     h623e0ac_2          1.1 MiB    conda  cctools_osx-arm64-1010.6-h623e0ac_2.conda
clang                  17.0.6     default_h360f5da_7  23.5 KiB   conda  clang-17.0.6-default_h360f5da_7.conda
clang-17               17.0.6     default_h146c034_7  699.2 KiB  conda  clang-17-17.0.6-default_h146c034_7.conda
clang_impl_osx-arm64   17.0.6     he47c785_23         17.5 KiB   conda  clang_impl_osx-arm64-17.0.6-he47c785_23.conda
clang_osx-arm64        17.0.6     h07b0088_23         20.7 KiB   conda  clang_osx-arm64-17.0.6-h07b0088_23.conda
clangxx                17.0.6     default_h360f5da_7  23.6 KiB   conda  clangxx-17.0.6-default_h360f5da_7.conda
compiler-rt            17.0.6     h856b3c1_2          92.7 KiB   conda  compiler-rt-17.0.6-h856b3c1_2.conda
compiler-rt_osx-arm64  17.0.6     h832e737_2          9.9 MiB    conda  compiler-rt_osx-arm64-17.0.6-h832e737_2.conda
ld64_osx-arm64         951.9      h3f9b568_2          993.9 KiB  conda  ld64_osx-arm64-951.9-h3f9b568_2.conda
libclang-cpp17         17.0.6     default_h146c034_7  11.8 MiB   conda  libclang-cpp17-17.0.6-default_h146c034_7.conda
libcxx                 19.1.4     ha82da77_0          508.5 KiB  conda  libcxx-19.1.4-ha82da77_0.conda
libcxx-devel           17.0.6     h86353a2_6          801.6 KiB  conda  libcxx-devel-17.0.6-h86353a2_6.conda
libexpat               2.6.4      h286801f_0          63.2 KiB   conda  libexpat-2.6.4-h286801f_0.conda
libffi                 3.4.2      h3422bc3_5          38.1 KiB   conda  libffi-3.4.2-h3422bc3_5.tar.bz2
libiconv               1.17       h0d3ecfb_2          660.6 KiB  conda  libiconv-1.17-h0d3ecfb_2.conda
libllvm17              17.0.6     h5090b49_2          23.5 MiB   conda  libllvm17-17.0.6-h5090b49_2.conda
libsqlite              3.47.0     hbaaea75_1          818 KiB    conda  libsqlite-3.47.0-hbaaea75_1.conda
libxml2                2.13.5     h376fa9f_0          568.4 KiB  conda  libxml2-2.13.5-h376fa9f_0.conda
libzlib                1.3.1      h8359307_2          45.3 KiB   conda  libzlib-1.3.1-h8359307_2.conda
llvm-tools             17.0.6     h5090b49_2          20.9 MiB   conda  llvm-tools-17.0.6-h5090b49_2.conda
mypy                   1.13.0     py312h0bf5046_0     9.4 MiB    conda  mypy-1.13.0-py312h0bf5046_0.conda
mypy_extensions        1.0.0      pyha770c72_0        10.2 KiB   conda  mypy_extensions-1.0.0-pyha770c72_0.conda
mypyc                  1.13.0     py312hf8ae5fc_0     11 KiB     conda  mypyc-1.13.0-py312hf8ae5fc_0.conda
ncurses                6.5        h7bae524_1          783.5 KiB  conda  ncurses-6.5-h7bae524_1.conda
openssl                3.4.0      h39f12f2_0          2.8 MiB    conda  openssl-3.4.0-h39f12f2_0.conda
psutil                 6.1.0      py312h0bf5046_0     481.9 KiB  conda  psutil-6.1.0-py312h0bf5046_0.conda
python                 3.12.7     h739c21a_0_cpython  12.4 MiB   conda  python-3.12.7-h739c21a_0_cpython.conda
python_abi             3.12       5_cp312             6.1 KiB    conda  python_abi-3.12-5_cp312.conda
readline               8.2        h92ec313_1          244.5 KiB  conda  readline-8.2-h92ec313_1.conda
setuptools             75.6.0     pyhff2d567_1        756.1 KiB  conda  setuptools-75.6.0-pyhff2d567_1.conda
sigtool                0.1.3      h44b9a77_0          205.3 KiB  conda  sigtool-0.1.3-h44b9a77_0.tar.bz2
tapi                   1300.6.5   h03f4b80_0          202.8 KiB  conda  tapi-1300.6.5-h03f4b80_0.conda
tk                     8.6.13     h5083fa2_1          3 MiB      conda  tk-8.6.13-h5083fa2_1.conda
tomli                  2.1.0      pyhff2d567_0        18.3 KiB   conda  tomli-2.1.0-pyhff2d567_0.conda
typing-extensions      4.12.2     hd8ed1ab_0          9.9 KiB    conda  typing-extensions-4.12.2-hd8ed1ab_0.conda
typing_extensions      4.12.2     pyha770c72_0        39 KiB     conda  typing_extensions-4.12.2-pyha770c72_0.conda
tzdata                 2024b      hc8b5060_0          119.5 KiB  conda  tzdata-2024b-hc8b5060_0.conda
xz                     5.2.6      h57fd34a_0          230.2 KiB  conda  xz-5.2.6-h57fd34a_0.tar.bz2
zstd                   1.5.6      hb46c0d2_0          395.6 KiB  conda  zstd-1.5.6-hb46c0d2_0.conda
```

### Environment info

```shell
       Environment: default
          Features: default
          Channels: conda-forge
  Dependency count: 1
      Dependencies: basedmypy
  Target platforms: osx-arm64
```

### PR DESCRIPTION
**Pull request by lucascolley**
fixes gh-11

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lucascolley** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@lucascolley - please go ahead add yourself as a maintainer too. As part of this PR. 
Appreciate the help
Thank you and Regards.

**Comment by lucascolley** [comment]
thanks @rxm7706 ! done

**Review by rxm7706 — APPROVED** [review]

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
